version: "3.9"
services:
  # [Database Server config]
  mariadb:
    build: ./requirements/mariadb/.

  # [Web Application Server config]
  wordpress:
    build: ./requirements/wordpress/.
    volumes: 
    - ./requirements/wordpress/WordPress:/var/www/html

  # [WebServer config]
  nginx:
    build: ./requirements/nginx/.
    ports:
    - "443:443"
    volumes: 
    - ./requirements/wordpress/WordPress:/var/www/html
